### ISSUE TITLE
yapf via Neoformat fails to run on a visual selection of a file

### ISSUE THREAD

**Issue by aetherknight** [sbdchd/neoformat#126]
Neoformat with `yapf` fails if Neoformat is run on a visual selection of a Python file that is itself not syntactically valid python.

### Working Example 1

For example:

```python
class SomeType(object):
    def __init__(self):
        pass

    def foo(self):
        bar = 'asdf'
        return bar
```

The following work:

`:Neoformat yapf`
`:%Neoformat yapf`

### Working Example 2

Also, the following works:

```python
# BEGIN VISUAL SELECTION
class SomeType(object):
    def __init__(self):
        pass
# END VISUAL SELECTION

    def foo(self):
        bar = 'asdf'
        return bar
```
`:'<,'>Neoformat yapf`

### Failing Example
However, the following fails:

```python

class SomeType(object):
# BEGIN VISUAL SELECTION
    def __init__(self):
        pass
# END VISUAL SELECTION

    def foo(self):
        bar = 'asdf'
        return bar
```
`:'<,'>Neoformat yapf`
I get the error message `Neoformat: formatters yapf failed to run`

If I enable verbose logging for neoformat:

```
Neoformat: ['    def __init__(self):', '        pass']
Neoformat: yapf
Neoformat: using stdin
Neoformat: ['Traceback (most recent call last):', '  File "/REDACTED/.pyenv/versions/2.7.11/bin/yapf", line 11, in <module>', '    sys.exit(run_main())', '  File "/REDACTED/.pyenv/versions/2.7.11/lib/python2.7/site-packages/yapf/__init__.py", line 306, in run_main', '    sys.exit(main(sys.argv))', '  File "/REDACTED/.pyenv/versions/2.7.11/lib/python2.7/site-packages/yapf/__init__.py", line 176, in main', '    verify=args.verify)', '  File "/REDACTED/.pyenv/versions/2.7.11/lib/python2.7/site-packages/yapf/yapflib/yapf_api.py", line 128, in FormatCode', '    tree = pytree_utils.ParseCodeToTree(unformatted_source)', '  File "/REDACTED/.pyenv/versions/2.7.11/lib/python2.7/site-packages/yapf/yapflib/pytree_utils.py", line 115, in ParseCodeToTree', '    raise e', '  File "<unknown>", line 1', '    def __init__(self):', '    ^', 'IndentationError: unexpected indent']
Neoformat: 1
Neoformat: trying next formatter
Neoformat: formatters yapf failed to run
```

Reformatted, the error message from yapf is:
```
Traceback (most recent call last):
  File "/REDACTED/.pyenv/versions/2.7.11/bin/yapf", line 11, in <module>
    sys.exit(run_main())
  File "/REDACTED/.pyenv/versions/2.7.11/lib/python2.7/site-packages/yapf/__init__.py", line 306, in run_main
    sys.exit(main(sys.argv))
  File "/REDACTED/.pyenv/versions/2.7.11/lib/python2.7/site-packages/yapf/__init__.py", line 176, in main
    verify=args.verify)
  File "/REDACTED/.pyenv/versions/2.7.11/lib/python2.7/site-packages/yapf/yapflib/yapf_api.py", line 128, in FormatCode
    tree = pytree_utils.ParseCodeToTree(unformatted_source)
  File "/REDACTED/.pyenv/versions/2.7.11/lib/python2.7/site-packages/yapf/yapflib/pytree_utils.py", line 115, in ParseCodeToTree
    raise e
  File "<unknown>", line 1
    def __init__(self):
    ^
IndentationError: unexpected indent
```

### Thoughts

In order to reformat just part of a file, `yapf` needs to be provided with the whole file, and the range to-be-reformatted needs to be specified with the command line argument `-l START-END` or `--lines START-END`. (https://github.com/google/yapf#usage)

I'm not sure if this is feasible in neoformat's current API/architecture, but it would be nice if this worked.

**Comment by darthdeus** [comment]
Is there any update/thoughts on this? I really like yapf, but this makes it impossible to use on an existing code base where I can't re-format whole files at once.

**Comment by sbdchd** [comment]
I am open to adding an option to give formatters context on visual selection.

I think Neoformat would need to use the entire buffer to ensure that the formatter has enough context so it doesn't get thrown off by indention and such.

Then it would only keep the lines at the visual selection.

But the issue is, how do you know where the lines are in the formatted output?

**Comment by darthdeus** [comment]
Isn't it enough to simply save the range of the visual selection, run yapf on it, and replace the same range with the new code?

It'd need to get the lowest indent level, remove it before piping to yapf, and then indent the output of yapf back again, so that one could for example format a method in a class without breaking the method indentation.

**Comment by mscheper** [comment]
@sbdchd:

> I am open to adding an option to give formatters context on visual selection

I think that would be the fix. Honestly, the reason I installed neoformat, instead of just setting `formatprg`, was because I assumed it would already do this, and pass it to yapf's `--lines` argument.

> But the issue is, how do you know where the lines are in the formatted output?

I think you would take the entire output from yapf, and just put the cursor back wherever it was. It would be nice if it moved to the new position, but I'm willing to live without that, if it gets this bug fixed quickly.

Thanks!
