### ISSUE TITLE
TSFMT reading from buffer errors

### ISSUE THREAD

**Issue by mhartington** [sbdchd/neoformat#15]
When reading from buffer instead of files, there seem to be some issues with escaped characters.

![](http://g.recordit.co/piYsilWsGG.gif)

Note if you change this to read from file instead, it works great. 
I will note that [vim-autoformat](https://github.com/Chiel92/vim-autoformat) does not have this issue, so it could need some escaping?

**Comment by sbdchd** [comment]
I am seeing this behavior as well.

Sending the data in via stdin, like vim-autoformat, seems to fix the issue.

I believe the issue is related to how neoformat saves the buffer data to `/tmp/` files for formatters to read from.
This results in the config options not being found by `tsfmt` and it defaults to the weird line endings.

I am currently working on a stdin option which fixes this issue.

**Comment by sbdchd** [comment]
Okay, Neoformat now sends buffer data to `tsfmt` via stdin and in my tests, it now works properly.

Can you confirm with the latest version?

**Comment by mhartington** [comment]
Well, it's not inserting extra characters, but it's also not formatting

**Comment by mhartington** [comment]
![](http://g.recordit.co/NvRMhePxCR.gif)

**Comment by sbdchd** [comment]
Can you update to the latest version and `set verbose=1`, run `:Neoformat`, and copy the output of `:messages`?

Thanks.

**Comment by mhartington** [comment]
```viml
Neoformat: ['import { Component } from ''@angular/core'';', '', 'import { NavController, Events } from ''ionic-angular'';', '', '@Component({', '  selector: ''page-home'',', '  templ
ateUrl: ''home.html''', '})', 'export class HomePage {', '    datatest: string = "old";', '    dataCala = 0;', '    constructor(', '      public navCtrl: NavController,', '      publ
ic events: Events', '    ) {', '        this.events.subscribe("data:changed", ()=>{', '          this.change();', '        });', '', '      }', '      change() {', '    console.log("
data changed!");', '    this.datatest = `new ${this.dataCala++}`', '  }', '}']
Neoformat: ['Error: No "files" or "filesGlob" section present in tsconfig.json', '    at readFilesFromTsconfig (/usr/local/lib/node_modules/typescript-formatter/lib/cli.js:158:15)',
'    at Command._action (/usr/local/lib/node_modules/typescript-formatter/lib/cli.js:47:21)', '    at Command.exec (/usr/local/lib/node_modules/typescript-formatter/node_modules/comm
andpost/lib/command.js:81:37)', '    at /usr/local/lib/node_modules/typescript-formatter/node_modules/commandpost/lib/command.js:118:26', '    at process._tickCallback (internal/proc
ess/next_tick.js:103:7)', '    at Module.runMain (module.js:606:11)', '    at run (bootstrap_node.js:394:7)', '    at startup (bootstrap_node.js:149:9)', '    at bootstrap_node.js:50
9:3']
Neoformat: 1
Neoformat: trying next formatter
Neoformat: attempted all formatters available for typescript
Neoformat: running basic format
Neoformat: aligning with basic formatter
Neoformat: converting tabs with basic formatter
Neoformat: trimming whitespace with basic formatter
```

**Comment by sbdchd** [comment]
It seems that `tsfmt` requires that you pass the name of the file when using `--stdin`

This errors:
```
cat test.ts | tsfmt --stdin
Error: No "files" or "filesGlob" section present in tsconfig.json
    at Object.readFilesFromTsconfig (/usr/local/lib/node_modules/typescript-formatter/lib/utils.js:54:15)
    at Command._action (/usr/local/lib/node_modules/typescript-formatter/lib/cli.js:48:29)
    at Command.exec (/usr/local/lib/node_modules/typescript-formatter/node_modules/commandpost/lib/command.js:186:37)
    at /usr/local/lib/node_modules/typescript-formatter/node_modules/commandpost/lib/command.js:233:26
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Function.Module.runMain (module.js:449:11)
    at startup (node.js:148:18)
    at node.js:405:3
```
This works:
```
cat test.ts | tsfmt --stdin test.ts
import { Component } from '@angular/core'

import { NavController } from 'ionic-angular';
@Component({
selector: 'page-home',
templateUrl: 'home.html'
})

export class HomePage {
contructor(public navCtrl: NavController) {

}
}
```

I have updated the `tsfmt` formatter definition to have the filename be passed as an argument. 

It should work. :crossed_fingers:

**Comment by mhartington** [comment]
Boom!  working nice now! Thanks!
